### ISSUE TITLE
tumsai nahi hoga gourav

### ISSUE THREAD

**Issue by AnishTiwari16** [GouravKumar13/React-Blogs#1]

**Comment by GouravKumar13** [comment]
@AnishTiwari16  you are fraud baag jao yaha se

**Comment by AnishTiwari16** [comment]
i am a hacker @GouravKumar13

**Comment by GouravKumar13** [comment]
go hack tesla then @AnishTiwari16

**Comment by AnishTiwari16** [comment]
elon musk is my son just like u @GouravKumar13

**Comment by GouravKumar13** [comment]
go talk to saluu bhai @AnishTiwari16
